 * Serving Flask app "app" (lazy loading)
 * Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "app.py", line 210, in <module>
    app.run(debug = True,port=8000)
  File "/var/www/net/venv/lib/python3.6/site-packages/flask/app.py", line 944, in run
    run_simple(host, port, self, **options)
  File "/var/www/net/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 987, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "app" (lazy loading)
 * Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "app.py", line 210, in <module>
    app.run(debug = True,port=8000)
  File "/var/www/net/venv/lib/python3.6/site-packages/flask/app.py", line 944, in run
    run_simple(host, port, self, **options)
  File "/var/www/net/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 987, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "app" (lazy loading)
 * Environment: development
 * Debug mode: on
Traceback (most recent call last):
  File "app.py", line 210, in <module>
    app.run(debug = True,port=8000)
  File "/var/www/net/venv/lib/python3.6/site-packages/flask/app.py", line 944, in run
    run_simple(host, port, self, **options)
  File "/var/www/net/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 987, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
